In [1]:
import numpy as np

In [2]:
np.random.seed(1)

# we use relu as activation function, basically if x > 0, return x, else return 0
def relu(x):
    return (x > 0) * x

# derivative of relu, if x > 0, return 1, else return 0
def relu2deriv(output):
    return output > 0

In [4]:
# This whole lights example is a xor problem, if the first light is on, the second light is off, then we should walk
# we use 2 layers of neural network to solve this problem
lights = np.array([[1, 0, 1],
                   [0, 1, 1],
                   [0, 0, 1],
                   [1, 1, 1]])

walk_stop = np.array([[1, 1, 0, 0]]).T
alpha = 0.2
hidden_size = 4

weights_0_1 = 2 * np.random.random((3, hidden_size)) - 1
weights_1_2 = 2 * np.random.random((hidden_size, 1)) - 1
print(weights_0_1)

[[ 0.48592313  0.65281058  0.55586494  0.33712176]
 [-0.33939986  0.53146812 -0.35305256  0.85016564]
 [-0.98817535 -0.50033869  0.23602321  0.79140387]]


In [5]:
for iteration in range(60):
    layer_2_error = 0
    for i in range(len(lights)):
        layer_0 = lights[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_0_1))
        layer_2 = np.dot(layer_1, weights_1_2)
        
        layer_2_error += np.sum((layer_2 - walk_stop[i:i+1]) ** 2)
        layer_2_delta = (walk_stop[i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)
        
        weights_1_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1 += alpha * layer_0.T.dot(layer_1_delta)
    if iteration % 10 == 9:
        print("Error: " + str(layer_2_error))

Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05


In [ ]:
#TODO: REBUILD FROM MEMORY

In [70]:
np.random.seed(1)
def relu2(output):
    return (output > 0) * output

def relu2der(output):
    return output > 0

lights = np.array([[1, 0, 1],
                   [0, 1, 1],
                   [0, 0, 1],
                   [1, 1, 1]])

walk_stop = np.array([[1, 1, 0, 0]])
alpha = 0.2
hidden_size = 4

weights_0_1_2 = 2 * np.random.random((lights[0].size, hidden_size)) - 1
weights_1_2_2 = 2 * np.random.random((hidden_size,1)) - 1

for iteration in range(60):
    layer_2_error = 0
    index = 0
    for i in range(len(lights)):
        input = lights[i:i+1]
        layer_1 = np.dot(input,weights_0_1_2)
        layer_1 = relu2(layer_1)
        layer_2 = np.dot(layer_1, weights_1_2_2)
        
        layer_2_error += np.sum((layer_2 - walk_stop[0][i:i+1]) ** 2)
        layer_2_delta = (walk_stop[0][i:i+1] - layer_2)
        layer_1_delta = layer_2_delta.dot(weights_1_2_2.T) * relu2der(layer_1)
        
        weights_1_2_2 += alpha * layer_1.T.dot(layer_2_delta)
        weights_0_1_2 += alpha * input.T.dot(layer_1_delta)
    if iteration % 10 == 9:
        print("Error: " + str(layer_2_error))

Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05
